unset APP_ID
unset API_TOKEN
unset ASSET
unset EXPIRY
unset STAKE
unset TIMEFRAME
unset TELEGRAM_TOKEN
unset TELEGRAM_CHAT_ID
unset BACKTEST

unset MODEL_TYPE
unset MODEL_PATH_LSTM
unset MODEL_PATH_XGB
unset MODEL_PATH_RL
unset SIGNAL_THRESHOLD
unset SEQUENCE_LENGTH

unset MAX_CONSECUTIVE_LOSSES
unset TRADE_RISK_PERCENT
unset MIN_BALANCE
unset MARTINGALE_MODE

unset HISTORICAL_DATA_PATH
unset SAVE_TRADE_HISTORY
unset TRADE_HISTORY_PATH
